# Below could be overwritten by specific env.
my.yml: emptyYml


#spring:
#    profiles: test
#name: test-YAML
#environment: test
#servers:
#    - www.abc.test.com
#    - www.xyz.test.com
#
#---
#spring:
#    profiles: prod
#name: prod-YAML
#environment: production
#servers:
#    - www.abc.com
#    - www.xyz.com
#benjiStaticYml: testStaticYml
#---
#spring:
#profiles: dev
#name: dev-YAML
#environment: dev
#servers:
#    - www.devabc.com
#    - www.devxyz.com
#benjiStaticYml: testStaticYml